server:
  # 服务端口
  port: 9001
spring:
  application:
    #指定服务名
    name: tensquare-base
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.134:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  #JPA的整合配置
  jpa:
    database: mysql
    show-sql: true
